/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 0.0.1
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_CppApi_WRAP_H_
#define SWIG_CppApi_WRAP_H_

class SwigDirector_Parent : public Parent, public Swig::Director {

public:
    SwigDirector_Parent();
    virtual ~SwigDirector_Parent();
    virtual int WhatAmI();
    virtual int DoSomethingElse(int a, int b);

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback1_t)(int, int);
    void swig_connect_director(SWIG_Callback0_t callbackWhatAmI, SWIG_Callback1_t callbackDoSomethingElse);

private:
    SWIG_Callback0_t swig_callbackWhatAmI;
    SWIG_Callback1_t swig_callbackDoSomethingElse;
    void swig_init_callbacks();
};

class SwigDirector_VectorConsumer : public VectorConsumer, public Swig::Director {

public:
    SwigDirector_VectorConsumer();
    virtual int VectorTakerPtr3(CVector3 *pVec);
    virtual int VectorTakerRef3(CVector3 &rVec);
    virtual int VectorTakerVal3(CVector3 vec);
    virtual CVector3 GimmeSomeVector();
    virtual int VectorTakerPtr4(CVector4 *pVec);
    virtual int VectorTakerRef4(CVector4 &rVec);
    virtual int VectorTakerVal4(CVector4 vec);

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef int (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef int (SWIGSTDCALL* SWIG_Callback2_t)(CVector3_POD /* CVector3_ctype_out */);
    typedef CVector3 /* CVector3_ctype */ (SWIGSTDCALL* SWIG_Callback3_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback4_t)(void *);
    typedef int (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef int (SWIGSTDCALL* SWIG_Callback6_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackVectorTakerPtr3, SWIG_Callback1_t callbackVectorTakerRef3, SWIG_Callback2_t callbackVectorTakerVal3, SWIG_Callback3_t callbackGimmeSomeVector, SWIG_Callback4_t callbackVectorTakerPtr4, SWIG_Callback5_t callbackVectorTakerRef4, SWIG_Callback6_t callbackVectorTakerVal4);

private:
    SWIG_Callback0_t swig_callbackVectorTakerPtr3;
    SWIG_Callback1_t swig_callbackVectorTakerRef3;
    SWIG_Callback2_t swig_callbackVectorTakerVal3;
    SWIG_Callback3_t swig_callbackGimmeSomeVector;
    SWIG_Callback4_t swig_callbackVectorTakerPtr4;
    SWIG_Callback5_t swig_callbackVectorTakerRef4;
    SWIG_Callback6_t swig_callbackVectorTakerVal4;
    void swig_init_callbacks();
};


#endif
