code^
 Directory.Build.props^
 src\Tools\BlenderScripts\addons\io_export_fus\__init__.py^
 dis\DnTemplate\template\Fusee_App.csproj^
 dis\VSTemplate\VSIX\Properties\AssemblyInfo.cs^
 dis\VSTemplate\VSTemplate\Properties\AssemblyInfo.cs^
 dis\VSTemplate\VSTemplate\Android\Android.csproj^
 dis\VSTemplate\VSTemplate\Core\Core.csproj^
 dis\VSTemplate\VSTemplate\Desktop\Desktop.csproj^
 dis\VSTemplate\VSIX\source.extension.vsixmanifest^
