// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Batch testing", Scope = "member", Target = "~M:Fusee.Tests.Xirkit.ConversionTest.ConvertFromBool(System.Int32,System.Single,System.Double,System.Boolean,System.String,Fusee.Math.Core.double2,Fusee.Math.Core.double3,Fusee.Math.Core.double4,Fusee.Math.Core.double4x4,Fusee.Math.Core.float2,Fusee.Math.Core.float3,Fusee.Math.Core.float4,Fusee.Math.Core.float4x4)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Batch testing", Scope = "member", Target = "~M:Fusee.Tests.Xirkit.ConversionTest.ConvertFromDouble2(System.Int32,System.Single,System.Double,System.Boolean,System.String,Fusee.Math.Core.double2,Fusee.Math.Core.double3,Fusee.Math.Core.double4,Fusee.Math.Core.double4x4,Fusee.Math.Core.float2,Fusee.Math.Core.float3,Fusee.Math.Core.float4,Fusee.Math.Core.float4x4)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Batch testing", Scope = "member", Target = "~M:Fusee.Tests.Xirkit.ConversionTest.ConvertFromDouble3(System.Int32,System.Single,System.Double,System.Boolean,System.String,Fusee.Math.Core.double2,Fusee.Math.Core.double3,Fusee.Math.Core.double4,Fusee.Math.Core.double4x4,Fusee.Math.Core.float2,Fusee.Math.Core.float3,Fusee.Math.Core.float4,Fusee.Math.Core.float4x4)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Batch testing", Scope = "member", Target = "~M:Fusee.Tests.Xirkit.ConversionTest.ConvertFromDouble4(System.Int32,System.Single,System.Double,System.Boolean,System.String,Fusee.Math.Core.double2,Fusee.Math.Core.double3,Fusee.Math.Core.double4,Fusee.Math.Core.double4x4,Fusee.Math.Core.float2,Fusee.Math.Core.float3,Fusee.Math.Core.float4,Fusee.Math.Core.float4x4)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Batch testing", Scope = "member", Target = "~M:Fusee.Tests.Xirkit.ConversionTest.ConvertFromDouble4x4(System.Int32,System.Single,System.Double,System.Boolean,System.String,Fusee.Math.Core.double2,Fusee.Math.Core.double3,Fusee.Math.Core.double4,Fusee.Math.Core.double4x4,Fusee.Math.Core.float2,Fusee.Math.Core.float3,Fusee.Math.Core.float4,Fusee.Math.Core.float4x4)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Batch testing", Scope = "member", Target = "~M:Fusee.Tests.Xirkit.ConversionTest.ConvertFromFloat2(System.Int32,System.Single,System.Double,System.Boolean,System.String,Fusee.Math.Core.double2,Fusee.Math.Core.double3,Fusee.Math.Core.double4,Fusee.Math.Core.double4x4,Fusee.Math.Core.float2,Fusee.Math.Core.float3,Fusee.Math.Core.float4,Fusee.Math.Core.float4x4)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Batch testing", Scope = "member", Target = "~M:Fusee.Tests.Xirkit.ConversionTest.ConvertFromFloat3(System.Int32,System.Single,System.Double,System.Boolean,System.String,Fusee.Math.Core.double2,Fusee.Math.Core.double3,Fusee.Math.Core.double4,Fusee.Math.Core.double4x4,Fusee.Math.Core.float2,Fusee.Math.Core.float3,Fusee.Math.Core.float4,Fusee.Math.Core.float4x4)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Batch testing", Scope = "member", Target = "~M:Fusee.Tests.Xirkit.ConversionTest.ConvertFromFloat4(System.Int32,System.Single,System.Double,System.Boolean,System.String,Fusee.Math.Core.double2,Fusee.Math.Core.double3,Fusee.Math.Core.double4,Fusee.Math.Core.double4x4,Fusee.Math.Core.float2,Fusee.Math.Core.float3,Fusee.Math.Core.float4,Fusee.Math.Core.float4x4)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Batch testing", Scope = "member", Target = "~M:Fusee.Tests.Xirkit.ConversionTest.ConvertFromFloat4x4(System.Int32,System.Single,System.Double,System.Boolean,System.String,Fusee.Math.Core.double2,Fusee.Math.Core.double3,Fusee.Math.Core.double4,Fusee.Math.Core.double4x4,Fusee.Math.Core.float2,Fusee.Math.Core.float3,Fusee.Math.Core.float4,Fusee.Math.Core.float4x4)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Batch testing", Scope = "member", Target = "~M:Fusee.Tests.Xirkit.ConversionTest.ConvertFromString(System.Int32,System.Single,System.Double,System.Boolean,System.String,Fusee.Math.Core.double2,Fusee.Math.Core.double3,Fusee.Math.Core.double4,Fusee.Math.Core.double4x4,Fusee.Math.Core.float2,Fusee.Math.Core.float3,Fusee.Math.Core.float4,Fusee.Math.Core.float4x4)")]
[assembly: SuppressMessage("Usage", "xUnit1026:Theory methods should use all of their parameters", Justification = "Batch testing", Scope = "member", Target = "~M:Fusee.Tests.Xirkit.ConversionTest.ConvertFromString(System.Int32,System.Single,System.Double,System.Boolean,System.String,Fusee.Math.Core.double2,Fusee.Math.Core.double3,Fusee.Math.Core.double4,Fusee.Math.Core.double4x4,Fusee.Math.Core.float2,Fusee.Math.Core.float3,Fusee.Math.Core.float4,Fusee.Math.Core.float4x4)")]