// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double3.b")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double3.g")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double3.r")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double3.xy")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double3.xyz")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double3.xzy")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double3.yxz")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double3.yzx")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double3.zxy")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double3.zyx")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double4.a")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double4.b")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double4.g")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double4.r")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double4.rgb")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double4.xy")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.double4.xyz")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float2.g")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float2.r")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float2.rg")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float2.xy")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float2.yx")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float3.b")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float3.g")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float3.r")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float3.xy")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float3.xyz")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float3.xz")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float3.xzy")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float3.yx")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float3.yxz")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float3.yz")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float3.yzx")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float3.zx")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float3.zxy")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float3.zy")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float3.zyx")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float4.a")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float4.b")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float4.g")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float4.r")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float4.rg")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float4.rgb")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float4.xy")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.float4.xyz")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.int3.b")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.int3.g")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.int3.r")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.Quaternion.w")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.Quaternion.x")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.Quaternion.xyz")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.Quaternion.y")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.Quaternion.z")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.QuaternionD.w")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.QuaternionD.x")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.QuaternionD.xyz")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.QuaternionD.y")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "member", Target = "~P:Fusee.Math.Core.QuaternionD.z")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "type", Target = "~T:Fusee.Math.Core.double2")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "type", Target = "~T:Fusee.Math.Core.double3")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "type", Target = "~T:Fusee.Math.Core.double4")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "type", Target = "~T:Fusee.Math.Core.double4x4")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "type", Target = "~T:Fusee.Math.Core.float2")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "type", Target = "~T:Fusee.Math.Core.float3")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "type", Target = "~T:Fusee.Math.Core.float3x3")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "type", Target = "~T:Fusee.Math.Core.float4")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "type", Target = "~T:Fusee.Math.Core.float4x4")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "API design", Scope = "type", Target = "~T:Fusee.Math.Core.int3")]