/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

public class AliasTrans : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AliasTrans(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AliasTrans obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public static AliasTrans Alloc() {
    global::System.IntPtr cPtr = C4dApiPINVOKE.AliasTrans_Alloc();
    AliasTrans ret = (cPtr == global::System.IntPtr.Zero) ? null : new AliasTrans(cPtr, false);
    return ret;
  }

  public static void Free(SWIGTYPE_p_p_AliasTrans link) {
    C4dApiPINVOKE.AliasTrans_Free(SWIGTYPE_p_p_AliasTrans.getCPtr(link));
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Init(BaseDocument doc) {
    bool ret = C4dApiPINVOKE.AliasTrans_Init(swigCPtr, BaseDocument.getCPtr(doc));
    return ret;
  }

  public void Translate(bool connect_oldgoals) {
    C4dApiPINVOKE.AliasTrans_Translate(swigCPtr, connect_oldgoals);
  }

}

}
