//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum ANIMATEFLAGS {
  ANIMATEFLAGS_0 = 0,
  ANIMATEFLAGS_NO_PARTICLES = (1 << 2),
  ANIMATEFLAGS_NO_CHILDREN = (1 << 6),
  ANIMATEFLAGS_INRENDER = (1 << 7),
  ANIMATEFLAGS_NO_MINMAX = (1 << 8),
  ANIMATEFLAGS_NO_NLA = (1 << 9),
  ANIMATEFLAGS_NLA_SUM = (1 << 10)
}

}
