/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

using System;
using System.Runtime.InteropServices;

public class AutoSpinLock : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AutoSpinLock(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(AutoSpinLock obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~AutoSpinLock() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          C4dApiPINVOKE.delete_AutoSpinLock(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public AutoSpinLock(GeSpinlock arg0) : this(C4dApiPINVOKE.new_AutoSpinLock__SWIG_0(GeSpinlock.getCPtr(arg0)), true) {
  }

  public AutoSpinLock() : this(C4dApiPINVOKE.new_AutoSpinLock__SWIG_1(), true) {
  }

  public void DoLock(GeSpinlock arg0) {
    C4dApiPINVOKE.AutoSpinLock_DoLock(swigCPtr, GeSpinlock.getCPtr(arg0));
  }

  public void Unlock() {
    C4dApiPINVOKE.AutoSpinLock_Unlock(swigCPtr);
  }

}

}
