//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum BUILDFLAGS {
  BUILDFLAGS_0 = 0,
  BUILDFLAGS_INTERNALRENDERER = (1 << 1),
  BUILDFLAGS_EXTERNALRENDERER = (1 << 2),
  BUILDFLAGS_ISOPARM = (1 << 3)
}

}
