//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum CAMORPH_MODE {
  CAMORPH_MODE_ABS = 0,
  CAMORPH_MODE_REL,
  CAMORPH_MODE_ROT,
  CAMORPH_MODE_CORRECTIONAL,
  CAMORPH_MODE_CORRECTIONAL_AREA,
  CAMORPH_MODE_AUTO = -1,
  CAMORPH_MODE_0 = 0
}

}
