/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

public enum CLOOP {
  CLOOP_OFF = 0,
  CLOOP_CONSTANT = 1,
  CLOOP_CONTINUE = 2,
  CLOOP_REPEAT = 3,
  CLOOP_OFFSETREPEAT = 4,
  CLOOP_OSCILLATE = 5
}

}
