/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

public class CustomGuiInExcludeLib : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CustomGuiInExcludeLib(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CustomGuiInExcludeLib obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CustomGuiInExcludeLib() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          C4dApiPINVOKE.delete_CustomGuiInExcludeLib(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_m_iIncludeExcludeData__f_p_BaseList2D_Int32__Bool InsertObject {
    set {
      C4dApiPINVOKE.CustomGuiInExcludeLib_InsertObject_set(swigCPtr, SWIGTYPE_m_iIncludeExcludeData__f_p_BaseList2D_Int32__Bool.getCMemberPtr(value));
    } 
    get {
      string cMemberPtr = C4dApiPINVOKE.CustomGuiInExcludeLib_InsertObject_get(swigCPtr);
      SWIGTYPE_m_iIncludeExcludeData__f_p_BaseList2D_Int32__Bool ret = (cMemberPtr == null) ? null : new SWIGTYPE_m_iIncludeExcludeData__f_p_BaseList2D_Int32__Bool(cMemberPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_p_BaseList2D__Int32 GetObjectIndex {
    set {
      C4dApiPINVOKE.CustomGuiInExcludeLib_GetObjectIndex_set(swigCPtr, SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_p_BaseList2D__Int32.getCMemberPtr(value));
    } 
    get {
      string cMemberPtr = C4dApiPINVOKE.CustomGuiInExcludeLib_GetObjectIndex_get(swigCPtr);
      SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_p_BaseList2D__Int32 ret = (cMemberPtr == null) ? null : new SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_p_BaseList2D__Int32(cMemberPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_m_iIncludeExcludeData__f_Int32__Bool DeleteObject {
    set {
      C4dApiPINVOKE.CustomGuiInExcludeLib_DeleteObject_set(swigCPtr, SWIGTYPE_m_iIncludeExcludeData__f_Int32__Bool.getCMemberPtr(value));
    } 
    get {
      string cMemberPtr = C4dApiPINVOKE.CustomGuiInExcludeLib_DeleteObject_get(swigCPtr);
      SWIGTYPE_m_iIncludeExcludeData__f_Int32__Bool ret = (cMemberPtr == null) ? null : new SWIGTYPE_m_iIncludeExcludeData__f_Int32__Bool(cMemberPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_m_iIncludeExcludeData__f___Int32 GetObjectCount {
    set {
      C4dApiPINVOKE.CustomGuiInExcludeLib_GetObjectCount_set(swigCPtr, SWIGTYPE_m_iIncludeExcludeData__f___Int32.getCMemberPtr(value));
    } 
    get {
      string cMemberPtr = C4dApiPINVOKE.CustomGuiInExcludeLib_GetObjectCount_get(swigCPtr);
      SWIGTYPE_m_iIncludeExcludeData__f___Int32 ret = (cMemberPtr == null) ? null : new SWIGTYPE_m_iIncludeExcludeData__f___Int32(cMemberPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_m_iIncludeExcludeData__f_Int32__Int32 GetFlags {
    set {
      C4dApiPINVOKE.CustomGuiInExcludeLib_GetFlags_set(swigCPtr, SWIGTYPE_m_iIncludeExcludeData__f_Int32__Int32.getCMemberPtr(value));
    } 
    get {
      string cMemberPtr = C4dApiPINVOKE.CustomGuiInExcludeLib_GetFlags_get(swigCPtr);
      SWIGTYPE_m_iIncludeExcludeData__f_Int32__Int32 ret = (cMemberPtr == null) ? null : new SWIGTYPE_m_iIncludeExcludeData__f_Int32__Int32(cMemberPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_Int32__p_BaseList2D ObjectFromIndex {
    set {
      C4dApiPINVOKE.CustomGuiInExcludeLib_ObjectFromIndex_set(swigCPtr, SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_Int32__p_BaseList2D.getCMemberPtr(value));
    } 
    get {
      string cMemberPtr = C4dApiPINVOKE.CustomGuiInExcludeLib_ObjectFromIndex_get(swigCPtr);
      SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_Int32__p_BaseList2D ret = (cMemberPtr == null) ? null : new SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_Int32__p_BaseList2D(cMemberPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_Int32__p_InclusionTable BuildInclusionTable {
    set {
      C4dApiPINVOKE.CustomGuiInExcludeLib_BuildInclusionTable_set(swigCPtr, SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_Int32__p_InclusionTable.getCMemberPtr(value));
    } 
    get {
      string cMemberPtr = C4dApiPINVOKE.CustomGuiInExcludeLib_BuildInclusionTable_get(swigCPtr);
      SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_Int32__p_InclusionTable ret = (cMemberPtr == null) ? null : new SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_Int32__p_InclusionTable(cMemberPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_m_iInclusionTable__f_p_BaseList2D__Bool Check {
    set {
      C4dApiPINVOKE.CustomGuiInExcludeLib_Check_set(swigCPtr, SWIGTYPE_m_iInclusionTable__f_p_BaseList2D__Bool.getCMemberPtr(value));
    } 
    get {
      string cMemberPtr = C4dApiPINVOKE.CustomGuiInExcludeLib_Check_get(swigCPtr);
      SWIGTYPE_m_iInclusionTable__f_p_BaseList2D__Bool ret = (cMemberPtr == null) ? null : new SWIGTYPE_m_iInclusionTable__f_p_BaseList2D__Bool(cMemberPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_m_iInclusionTable__f___Int32 GetObjectCountT {
    set {
      C4dApiPINVOKE.CustomGuiInExcludeLib_GetObjectCountT_set(swigCPtr, SWIGTYPE_m_iInclusionTable__f___Int32.getCMemberPtr(value));
    } 
    get {
      string cMemberPtr = C4dApiPINVOKE.CustomGuiInExcludeLib_GetObjectCountT_get(swigCPtr);
      SWIGTYPE_m_iInclusionTable__f___Int32 ret = (cMemberPtr == null) ? null : new SWIGTYPE_m_iInclusionTable__f___Int32(cMemberPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_m_iInclusionTable__f_Int32__p_BaseList2D GetObject {
    set {
      C4dApiPINVOKE.CustomGuiInExcludeLib_GetObject_set(swigCPtr, SWIGTYPE_m_iInclusionTable__f_Int32__p_BaseList2D.getCMemberPtr(value));
    } 
    get {
      string cMemberPtr = C4dApiPINVOKE.CustomGuiInExcludeLib_GetObject_get(swigCPtr);
      SWIGTYPE_m_iInclusionTable__f_Int32__p_BaseList2D ret = (cMemberPtr == null) ? null : new SWIGTYPE_m_iInclusionTable__f_Int32__p_BaseList2D(cMemberPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_iInclusionTable__void LIB_FreeInclusionTable {
    set {
      C4dApiPINVOKE.CustomGuiInExcludeLib_LIB_FreeInclusionTable_set(swigCPtr, SWIGTYPE_p_f_p_iInclusionTable__void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = C4dApiPINVOKE.CustomGuiInExcludeLib_LIB_FreeInclusionTable_get(swigCPtr);
      SWIGTYPE_p_f_p_iInclusionTable__void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_iInclusionTable__void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_m_iIncludeExcludeData__f_Int32__p_BaseContainer GetData {
    set {
      C4dApiPINVOKE.CustomGuiInExcludeLib_GetData_set(swigCPtr, SWIGTYPE_m_iIncludeExcludeData__f_Int32__p_BaseContainer.getCMemberPtr(value));
    } 
    get {
      string cMemberPtr = C4dApiPINVOKE.CustomGuiInExcludeLib_GetData_get(swigCPtr);
      SWIGTYPE_m_iIncludeExcludeData__f_Int32__p_BaseContainer ret = (cMemberPtr == null) ? null : new SWIGTYPE_m_iIncludeExcludeData__f_Int32__p_BaseContainer(cMemberPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_m_iInclusionTable__f_p_BaseList2D_r_Int32__Bool CheckFlags {
    set {
      C4dApiPINVOKE.CustomGuiInExcludeLib_CheckFlags_set(swigCPtr, SWIGTYPE_m_iInclusionTable__f_p_BaseList2D_r_Int32__Bool.getCMemberPtr(value));
    } 
    get {
      string cMemberPtr = C4dApiPINVOKE.CustomGuiInExcludeLib_CheckFlags_get(swigCPtr);
      SWIGTYPE_m_iInclusionTable__f_p_BaseList2D_r_Int32__Bool ret = (cMemberPtr == null) ? null : new SWIGTYPE_m_iInclusionTable__f_p_BaseList2D_r_Int32__Bool(cMemberPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_m_iIncludeExcludeData__f_Int32_Int32__void SetFlags {
    set {
      C4dApiPINVOKE.CustomGuiInExcludeLib_SetFlags_set(swigCPtr, SWIGTYPE_m_iIncludeExcludeData__f_Int32_Int32__void.getCMemberPtr(value));
    } 
    get {
      string cMemberPtr = C4dApiPINVOKE.CustomGuiInExcludeLib_SetFlags_get(swigCPtr);
      SWIGTYPE_m_iIncludeExcludeData__f_Int32_Int32__void ret = (cMemberPtr == null) ? null : new SWIGTYPE_m_iIncludeExcludeData__f_Int32_Int32__void(cMemberPtr, false);
      return ret;
    } 
  }

  public CustomGuiInExcludeLib() : this(C4dApiPINVOKE.new_CustomGuiInExcludeLib(), true) {
  }

}

}
