//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum DESCIDINFOFLAGS {
  DESCIDINFOFLAGS_NONE = 0,
  DESCIDINFOFLAGS_INPORT = 1 << 0,
  DESCIDINFOFLAGS_INPORT_CONNECTED = 1 << 1,
  DESCIDINFOFLAGS_OUTPORT = 1 << 2,
  DESCIDINFOFLAGS_OUTPORT_CONNECTED = 1 << 3
}

}
