/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

using System;
using System.Runtime.InteropServices;

public class DescriptionPopup : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DescriptionPopup(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DescriptionPopup obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DescriptionPopup() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          C4dApiPINVOKE.delete_DescriptionPopup(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public DescID id {
    set {
      C4dApiPINVOKE.DescriptionPopup_id_set(swigCPtr, DescID.getCPtr(value));
    } 
    get {
      IntPtr cPtr = C4dApiPINVOKE.DescriptionPopup_id_get(swigCPtr);
      DescID ret = (cPtr == IntPtr.Zero) ? null : new DescID(cPtr, false);
      return ret;
    } 
  }

  public int chosen {
    set {
      C4dApiPINVOKE.DescriptionPopup_chosen_set(swigCPtr, value);
    } 
    get {
      int ret = C4dApiPINVOKE.DescriptionPopup_chosen_get(swigCPtr);
      return ret;
    } 
  }

  public BaseContainer msg {
    set {
      C4dApiPINVOKE.DescriptionPopup_msg_set(swigCPtr, BaseContainer.getCPtr(value));
    } 
    get {
      IntPtr cPtr = C4dApiPINVOKE.DescriptionPopup_msg_get(swigCPtr);
      BaseContainer ret = (cPtr == IntPtr.Zero) ? null : new BaseContainer(cPtr, false);
      return ret;
    } 
  }

  public BaseContainer popup {
    set {
      C4dApiPINVOKE.DescriptionPopup_popup_set(swigCPtr, BaseContainer.getCPtr(value));
    } 
    get {
      IntPtr cPtr = C4dApiPINVOKE.DescriptionPopup_popup_get(swigCPtr);
      BaseContainer ret = (cPtr == IntPtr.Zero) ? null : new BaseContainer(cPtr, false);
      return ret;
    } 
  }

  public DescriptionPopup() : this(C4dApiPINVOKE.new_DescriptionPopup(), true) {
  }

}

}
