/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

public class DescriptionGetBitmap : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DescriptionGetBitmap(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DescriptionGetBitmap obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DescriptionGetBitmap() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          C4dApiPINVOKE.delete_DescriptionGetBitmap(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public DescID id {
    set {
      C4dApiPINVOKE.DescriptionGetBitmap_id_set(swigCPtr, DescID.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = C4dApiPINVOKE.DescriptionGetBitmap_id_get(swigCPtr);
      DescID ret = (cPtr == global::System.IntPtr.Zero) ? null : new DescID(cPtr, false);
      return ret;
    } 
  }

  public BaseBitmap bmp {
    set {
      C4dApiPINVOKE.DescriptionGetBitmap_bmp_set(swigCPtr, BaseBitmap.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = C4dApiPINVOKE.DescriptionGetBitmap_bmp_get(swigCPtr);
      BaseBitmap ret = (cPtr == global::System.IntPtr.Zero) ? null : new BaseBitmap(cPtr, false);
      return ret;
    } 
  }

  public ICONDATAFLAGS bmpflags {
    set {
      C4dApiPINVOKE.DescriptionGetBitmap_bmpflags_set(swigCPtr, (int)value);
    } 
    get {
      ICONDATAFLAGS ret = (ICONDATAFLAGS)C4dApiPINVOKE.DescriptionGetBitmap_bmpflags_get(swigCPtr);
      return ret;
    } 
  }

  public DescriptionGetBitmap() : this(C4dApiPINVOKE.new_DescriptionGetBitmap(), true) {
  }

}

}
