//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public class DocumentInfoClipData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DocumentInfoClipData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DocumentInfoClipData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DocumentInfoClipData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          C4dApiPINVOKE.delete_DocumentInfoClipData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public DocumentInfoClipData() : this(C4dApiPINVOKE.new_DocumentInfoClipData(), true) {
  }

  public AtomArray arr {
    set {
      C4dApiPINVOKE.DocumentInfoClipData_arr_set(swigCPtr, AtomArray.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = C4dApiPINVOKE.DocumentInfoClipData_arr_get(swigCPtr);
      AtomArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new AtomArray(cPtr, false);
      return ret;
    } 
  }

  public AliasTrans trans {
    set {
      C4dApiPINVOKE.DocumentInfoClipData_trans_set(swigCPtr, AliasTrans.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = C4dApiPINVOKE.DocumentInfoClipData_trans_get(swigCPtr);
      AliasTrans ret = (cPtr == global::System.IntPtr.Zero) ? null : new AliasTrans(cPtr, false);
      return ret;
    } 
  }

  public BaseContainer bcdata {
    set {
      C4dApiPINVOKE.DocumentInfoClipData_bcdata_set(swigCPtr, BaseContainer.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = C4dApiPINVOKE.DocumentInfoClipData_bcdata_get(swigCPtr);
      BaseContainer ret = (cPtr == global::System.IntPtr.Zero) ? null : new BaseContainer(cPtr, false);
      return ret;
    } 
  }

}

}
