//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum DRAW_ALPHA {
  DRAW_ALPHA_NONE = 10,
  DRAW_ALPHA_INVERTED = 11,
  DRAW_ALPHA_NORMAL = 12,
  DRAW_ALPHA_FROM_IMAGE = 13,
  DRAW_ALPHA_NORMAL_FROM_IMAGE = 14
}

}
