/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

public enum EVENT {
  EVENT_0 = 0,
  EVENT_FORCEREDRAW = (1 << 0),
  EVENT_ANIMATE = (1 << 1),
  EVENT_NOEXPRESSION = (1 << 2),
  EVENT_GLHACK = (1 << 3),
  EVENT_CAMERAEXPRESSION = (1 << 4)
}

}
