//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum FILESELECTTYPE {
  FILESELECTTYPE_ANYTHING = 0,
  FILESELECTTYPE_IMAGES = 1,
  FILESELECTTYPE_SCENES = 2,
  FILESELECTTYPE_COFFEE = 3,
  FILESELECTTYPE_BODYPAINT = 4
}

}
