//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum GEMB {
  GEMB_OK = 0x0000,
  GEMB_OKCANCEL = 0x0001,
  GEMB_ABORTRETRYIGNORE = 0x0002,
  GEMB_YESNOCANCEL = 0x0003,
  GEMB_YESNO = 0x0004,
  GEMB_RETRYCANCEL = 0x0005,
  GEMB_FORCEDIALOG = 0x8000,
  GEMB_ICONSTOP = 0x0010,
  GEMB_ICONQUESTION = 0x0020,
  GEMB_ICONEXCLAMATION = 0x0030,
  GEMB_ICONASTERISK = 0x0040,
  GEMB_MULTILINE = 0x0080
}

}
