/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

public enum GETBRANCHINFO {
  GETBRANCHINFO_0 = 0,
  GETBRANCHINFO_ONLYWITHCHILDREN = (1 << 1),
  GETBRANCHINFO_GELISTNODES = (1 << 3),
  GETBRANCHINFO_ONLYMODIFIABLE = (1 << 4)
}

}
