//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum GvAnimHookType {
  GV_ANIM_HOOK_INIT = 0,
  GV_ANIM_HOOK_FREE,
  GV_ANIM_HOOK_MAIN
}

}
