/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

public enum GvBodyDefaultSize {
  GV_DEFAULT_BODY_WIDTH = 32,
  GV_DEFAULT_BODY_HEIGHT = 12
}

}
