//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum GvCalcFlags {
  GV_CALC_FLAG_NONE = (0),
  GV_CALC_FLAG_READ_ONLY = (1 << 0)
}

}
