/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

using System;
using System.Runtime.InteropServices;

public class GvPortList : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GvPortList(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GvPortList obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int GetCount() {
    int ret = C4dApiPINVOKE.GvPortList_GetCount(swigCPtr);
    return ret;
  }

  public bool Append(GvPortListEntry e) {
    bool ret = C4dApiPINVOKE.GvPortList_Append(swigCPtr, GvPortListEntry.getCPtr(e));
    return ret;
  }

  public bool Remove(GvPortListEntry e) {
    bool ret = C4dApiPINVOKE.GvPortList_Remove(swigCPtr, GvPortListEntry.getCPtr(e));
    return ret;
  }

  public GvPortListEntry GetIndex(int i) {
    IntPtr cPtr = C4dApiPINVOKE.GvPortList_GetIndex(swigCPtr, i);
    GvPortListEntry ret = (cPtr == IntPtr.Zero) ? null : new GvPortListEntry(cPtr, false);
    return ret;
  }

  public void FlushAll() {
    C4dApiPINVOKE.GvPortList_FlushAll(swigCPtr);
  }

  public static GvPortList Alloc() {
    IntPtr cPtr = C4dApiPINVOKE.GvPortList_Alloc();
    GvPortList ret = (cPtr == IntPtr.Zero) ? null : new GvPortList(cPtr, false);
    return ret;
  }

  public static void Free(SWIGTYPE_p_p_GvPortList list) {
    C4dApiPINVOKE.GvPortList_Free(SWIGTYPE_p_p_GvPortList.getCPtr(list));
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
