//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum GvState {
  GV_STATE_NORMAL = 0,
  GV_STATE_SELECTED,
  GV_STATE_DISABLED,
  GV_STATE_SELECTED_AND_DISABLED,
  GV_NR_OF_STATES
}

}
