/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

using System;
using System.Runtime.InteropServices;

public class GvWorld : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GvWorld(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GvWorld obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public GvNodeMaster AllocNodeMaster(BaseList2D arg0, bool add_to_list, bool send_messages) {
    IntPtr cPtr = C4dApiPINVOKE.GvWorld_AllocNodeMaster__SWIG_0(swigCPtr, BaseList2D.getCPtr(arg0), add_to_list, send_messages);
    GvNodeMaster ret = (cPtr == IntPtr.Zero) ? null : new GvNodeMaster(cPtr, false);
    return ret;
  }

  public GvNodeMaster AllocNodeMaster(BaseList2D arg0, bool add_to_list) {
    IntPtr cPtr = C4dApiPINVOKE.GvWorld_AllocNodeMaster__SWIG_1(swigCPtr, BaseList2D.getCPtr(arg0), add_to_list);
    GvNodeMaster ret = (cPtr == IntPtr.Zero) ? null : new GvNodeMaster(cPtr, false);
    return ret;
  }

  public GvNodeMaster AllocNodeMaster(BaseList2D arg0) {
    IntPtr cPtr = C4dApiPINVOKE.GvWorld_AllocNodeMaster__SWIG_2(swigCPtr, BaseList2D.getCPtr(arg0));
    GvNodeMaster ret = (cPtr == IntPtr.Zero) ? null : new GvNodeMaster(cPtr, false);
    return ret;
  }

  public void FreeNodeMaster(SWIGTYPE_p_p_GvNodeMaster master) {
    C4dApiPINVOKE.GvWorld_FreeNodeMaster(swigCPtr, SWIGTYPE_p_p_GvNodeMaster.getCPtr(master));
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public GvNodeGUI AllocNodeGUI(SWIGTYPE_p_GvShape shape, SWIGTYPE_p_GvShape group, int user_area_id) {
    IntPtr cPtr = C4dApiPINVOKE.GvWorld_AllocNodeGUI(swigCPtr, SWIGTYPE_p_GvShape.getCPtr(shape), SWIGTYPE_p_GvShape.getCPtr(group), user_area_id);
    GvNodeGUI ret = (cPtr == IntPtr.Zero) ? null : new GvNodeGUI(cPtr, false);
    return ret;
  }

  public void FreeNodeGUI(SWIGTYPE_p_p_GvNodeGUI gui) {
    C4dApiPINVOKE.GvWorld_FreeNodeGUI(swigCPtr, SWIGTYPE_p_p_GvNodeGUI.getCPtr(gui));
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_GvShape AllocShape() {
    IntPtr cPtr = C4dApiPINVOKE.GvWorld_AllocShape(swigCPtr);
    SWIGTYPE_p_GvShape ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_GvShape(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_GvShape AllocGroupShape() {
    IntPtr cPtr = C4dApiPINVOKE.GvWorld_AllocGroupShape(swigCPtr);
    SWIGTYPE_p_GvShape ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_GvShape(cPtr, false);
    return ret;
  }

  public void FreeShape(SWIGTYPE_p_p_GvShape shape) {
    C4dApiPINVOKE.GvWorld_FreeShape(swigCPtr, SWIGTYPE_p_p_GvShape.getCPtr(shape));
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool RegisterHook(GvHook hook, SWIGTYPE_p_void user) {
    bool ret = C4dApiPINVOKE.GvWorld_RegisterHook(swigCPtr, GvHook.getCPtr(hook), SWIGTYPE_p_void.getCPtr(user));
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool AttachHook(int hook_id, SWIGTYPE_p_f_p_BaseDocument_LONG__p_BaseList2D callback) {
    bool ret = C4dApiPINVOKE.GvWorld_AttachHook(swigCPtr, hook_id, SWIGTYPE_p_f_p_BaseDocument_LONG__p_BaseList2D.getCPtr(callback));
    return ret;
  }

  public void DetachHook(int hook_id) {
    C4dApiPINVOKE.GvWorld_DetachHook(swigCPtr, hook_id);
  }

  public BaseList2D GetHookInstance(BaseDocument doc, int hook_id) {
    IntPtr cPtr = C4dApiPINVOKE.GvWorld_GetHookInstance(swigCPtr, BaseDocument.getCPtr(doc), hook_id);
    BaseList2D ret = (cPtr == IntPtr.Zero) ? null : new BaseList2D(cPtr, false);
    return ret;
  }

  public bool SendHookMessage(BaseDocument doc, GvNodeMaster master, GvMessHook data, int owner_id) {
    bool ret = C4dApiPINVOKE.GvWorld_SendHookMessage(swigCPtr, BaseDocument.getCPtr(doc), GvNodeMaster.getCPtr(master), GvMessHook.getCPtr(data), owner_id);
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool SendOperatorMessage(BaseDocument doc, int message_id, SWIGTYPE_p_void data) {
    bool ret = C4dApiPINVOKE.GvWorld_SendOperatorMessage(swigCPtr, BaseDocument.getCPtr(doc), message_id, SWIGTYPE_p_void.getCPtr(data));
    return ret;
  }

  public bool OpenDialog(int id, GvNodeMaster master) {
    bool ret = C4dApiPINVOKE.GvWorld_OpenDialog(swigCPtr, id, GvNodeMaster.getCPtr(master));
    return ret;
  }

  public void CloseDialog(int id) {
    C4dApiPINVOKE.GvWorld_CloseDialog(swigCPtr, id);
  }

  public void RedrawAll() {
    C4dApiPINVOKE.GvWorld_RedrawAll(swigCPtr);
  }

  public void RedrawMaster(GvNodeMaster master) {
    C4dApiPINVOKE.GvWorld_RedrawMaster(swigCPtr, GvNodeMaster.getCPtr(master));
  }

  public bool AttachNode(GvNodeMaster master, GvNode node, int x, int y) {
    bool ret = C4dApiPINVOKE.GvWorld_AttachNode(swigCPtr, GvNodeMaster.getCPtr(master), GvNode.getCPtr(node), x, y);
    return ret;
  }

  public string /* String_cstype */ GetString(string /* constString&_cstype */ title, string /* constString&_cstype */ default_value)  {  /* <String_csout> */
      string ret = C4dApiPINVOKE.GvWorld_GetString(swigCPtr, title, default_value);
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
      return ret;
   } /* </String_csout> */ 

  public double GetReal(string /* constString&_cstype */ title, double default_value) {
    double ret = C4dApiPINVOKE.GvWorld_GetReal(swigCPtr, title, default_value);
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetInteger(string /* constString&_cstype */ title, int default_value) {
    int ret = C4dApiPINVOKE.GvWorld_GetInteger(swigCPtr, title, default_value);
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetDataTypesMenu(BaseContainer bc, BaseContainer index, int first_menu_id, int first_sub_id, bool show_undefined_type, GvValueFlags flags) {
    int ret = C4dApiPINVOKE.GvWorld_GetDataTypesMenu__SWIG_0(swigCPtr, BaseContainer.getCPtr(bc), BaseContainer.getCPtr(index), first_menu_id, first_sub_id, show_undefined_type, (int)flags);
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetDataTypesMenu(BaseContainer bc, BaseContainer index, int first_menu_id, int first_sub_id, bool show_undefined_type) {
    int ret = C4dApiPINVOKE.GvWorld_GetDataTypesMenu__SWIG_1(swigCPtr, BaseContainer.getCPtr(bc), BaseContainer.getCPtr(index), first_menu_id, first_sub_id, show_undefined_type);
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetDataTypesMenu(BaseContainer bc, BaseContainer index, int first_menu_id, int first_sub_id) {
    int ret = C4dApiPINVOKE.GvWorld_GetDataTypesMenu__SWIG_2(swigCPtr, BaseContainer.getCPtr(bc), BaseContainer.getCPtr(index), first_menu_id, first_sub_id);
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetDataTypes(BaseContainer bc, GvDataOptions options, GvValueFlags flags) {
    int ret = C4dApiPINVOKE.GvWorld_GetDataTypes__SWIG_0(swigCPtr, BaseContainer.getCPtr(bc), (int)options, (int)flags);
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetDataTypes(BaseContainer bc, GvDataOptions options) {
    int ret = C4dApiPINVOKE.GvWorld_GetDataTypes__SWIG_1(swigCPtr, BaseContainer.getCPtr(bc), (int)options);
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetDataTypes(BaseContainer bc) {
    int ret = C4dApiPINVOKE.GvWorld_GetDataTypes__SWIG_2(swigCPtr, BaseContainer.getCPtr(bc));
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetDataTypesTable(SWIGTYPE_p_p_GvDataInfo info, SWIGTYPE_p_LONG count) {
    bool ret = C4dApiPINVOKE.GvWorld_GetDataTypesTable(swigCPtr, SWIGTYPE_p_p_GvDataInfo.getCPtr(info), SWIGTYPE_p_LONG.getCPtr(count));
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetDataTypeIndex(int id) {
    int ret = C4dApiPINVOKE.GvWorld_GetDataTypeIndex(swigCPtr, id);
    return ret;
  }

  public GvDataInfo GetDataTypeInfo(int id) {
    IntPtr cPtr = C4dApiPINVOKE.GvWorld_GetDataTypeInfo(swigCPtr, id);
    GvDataInfo ret = (cPtr == IntPtr.Zero) ? null : new GvDataInfo(cPtr, false);
    return ret;
  }

  public GvNodeGUI GetMasterGUI(GvNodeMaster master, SWIGTYPE_p_ULONG nr) {
    IntPtr cPtr = C4dApiPINVOKE.GvWorld_GetMasterGUI__SWIG_0(swigCPtr, GvNodeMaster.getCPtr(master), SWIGTYPE_p_ULONG.getCPtr(nr));
    GvNodeGUI ret = (cPtr == IntPtr.Zero) ? null : new GvNodeGUI(cPtr, false);
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GvNodeGUI GetMasterGUI(GvNodeMaster master) {
    IntPtr cPtr = C4dApiPINVOKE.GvWorld_GetMasterGUI__SWIG_1(swigCPtr, GvNodeMaster.getCPtr(master));
    GvNodeGUI ret = (cPtr == IntPtr.Zero) ? null : new GvNodeGUI(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_ULONG GetUniqueID() {
    SWIGTYPE_p_ULONG ret = new SWIGTYPE_p_ULONG(C4dApiPINVOKE.GvWorld_GetUniqueID(swigCPtr), true);
    return ret;
  }

  public BaseBitmap GetDefaultOperatorIcon(GvOperatorType type) {
    IntPtr cPtr = C4dApiPINVOKE.GvWorld_GetDefaultOperatorIcon(swigCPtr, (int)type);
    BaseBitmap ret = (cPtr == IntPtr.Zero) ? null : new BaseBitmap(cPtr, false);
    return ret;
  }

  public void SetPrefs(BaseContainer bc) {
    C4dApiPINVOKE.GvWorld_SetPrefs(swigCPtr, BaseContainer.getCPtr(bc));
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetPrefs(BaseContainer bc) {
    C4dApiPINVOKE.GvWorld_GetPrefs(swigCPtr, BaseContainer.getCPtr(bc));
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetDataTypeNames(BaseContainer bc, SWIGTYPE_p_LONG ids) {
    int ret = C4dApiPINVOKE.GvWorld_GetDataTypeNames(swigCPtr, BaseContainer.getCPtr(bc), SWIGTYPE_p_LONG.getCPtr(ids));
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GvNodeMaster GetMaster(int id) {
    IntPtr cPtr = C4dApiPINVOKE.GvWorld_GetMaster(swigCPtr, id);
    GvNodeMaster ret = (cPtr == IntPtr.Zero) ? null : new GvNodeMaster(cPtr, false);
    return ret;
  }

}

}
