/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

public enum HDIRTYFLAGS {
  HDIRTYFLAGS_0 = 0,
  HDIRTYFLAGS_ANIMATION = (1 << 0),
  HDIRTYFLAGS_OBJECT = (1 << 1),
  HDIRTYFLAGS_OBJECT_MATRIX = (1 << 2),
  HDIRTYFLAGS_OBJECT_HIERARCHY = (1 << 3),
  HDIRTYFLAGS_TAG = (1 << 4),
  HDIRTYFLAGS_MATERIAL = (1 << 5),
  HDIRTYFLAGS_SHADER = (1 << 6),
  HDIRTYFLAGS_RENDERSETTINGS = (1 << 7),
  HDIRTYFLAGS_VP = (1 << 8),
  HDIRTYFLAGS_FILTER = (1 << 9),
  HDIRTYFLAGS_NBITS = (1 << 10),
  HDIRTYFLAGS_ALL = -1
}

}
