/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

public enum ILLUMINATEFLAGS {
  ILLUMINATEFLAGS_0 = 0,
  ILLUMINATEFLAGS_SHADOW = (1 << 0),
  ILLUMINATEFLAGS_NOENVIRONMENT = (1 << 1),
  ILLUMINATEFLAGS_DISABLESHADOWMAP_CORRECTION = (1 << 20),
  ILLUMINATEFLAGS_DISABLESHADOWCASTERMP_CORRECTION = (1 << 21)
}

}
