//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum INITCALCULATION {
  INITCALCULATION_SURFACE = 0,
  INITCALCULATION_TRANSPARENCY = 1,
  INITCALCULATION_DISPLACEMENT = 3
}

}
