//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public class MaterialDragAndDrop : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MaterialDragAndDrop(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MaterialDragAndDrop obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MaterialDragAndDrop() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          C4dApiPINVOKE.delete_MaterialDragAndDrop(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public MaterialDragAndDrop() : this(C4dApiPINVOKE.new_MaterialDragAndDrop(), true) {
  }

  public BaseDocument doc {
    set {
      C4dApiPINVOKE.MaterialDragAndDrop_doc_set(swigCPtr, BaseDocument.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = C4dApiPINVOKE.MaterialDragAndDrop_doc_get(swigCPtr);
      BaseDocument ret = (cPtr == global::System.IntPtr.Zero) ? null : new BaseDocument(cPtr, false);
      return ret;
    } 
  }

  public BaseObject op {
    set {
      C4dApiPINVOKE.MaterialDragAndDrop_op_set(swigCPtr, BaseObject.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = C4dApiPINVOKE.MaterialDragAndDrop_op_get(swigCPtr);
      BaseObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new BaseObject(cPtr, false);
      return ret;
    } 
  }

  public BaseTag result {
    set {
      C4dApiPINVOKE.MaterialDragAndDrop_result_set(swigCPtr, BaseTag.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = C4dApiPINVOKE.MaterialDragAndDrop_result_get(swigCPtr);
      BaseTag ret = (cPtr == global::System.IntPtr.Zero) ? null : new BaseTag(cPtr, false);
      return ret;
    } 
  }

}

}
