/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

public enum MULTIPASSCHANNEL {
  MULTIPASSCHANNEL_0 = 0,
  MULTIPASSCHANNEL_IMAGELAYER = (1 << 0),
  MULTIPASSCHANNEL_MATERIALCHANNEL = (1 << 1)
}

}
