//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum OBJECTSTATE {
  OBJECTSTATE_EDITOR = 0,
  OBJECTSTATE_RENDER = 1,
  OBJECTSTATE_DEFORM = 2
}

}
