//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum OITMODE {
  OITMODE_OFF = 0,
  OITMODE_FIRST = 1,
  OITMODE_MIDDLE = 2,
  OITMODE_LAST = 3
}

}
