/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

using System;
using System.Runtime.InteropServices;

public class PolyInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PolyInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PolyInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PolyInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          C4dApiPINVOKE.delete_PolyInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_LONG face {
    set {
      C4dApiPINVOKE.PolyInfo_face_set(swigCPtr, SWIGTYPE_p_LONG.getCPtr(value));
    } 
    get {
      IntPtr cPtr = C4dApiPINVOKE.PolyInfo_face_get(swigCPtr);
      SWIGTYPE_p_LONG ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_LONG(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_LONG edge {
    set {
      C4dApiPINVOKE.PolyInfo_edge_set(swigCPtr, SWIGTYPE_p_LONG.getCPtr(value));
    } 
    get {
      IntPtr cPtr = C4dApiPINVOKE.PolyInfo_edge_get(swigCPtr);
      SWIGTYPE_p_LONG ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_LONG(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_CHAR mark {
    set {
      C4dApiPINVOKE.PolyInfo_mark_set(swigCPtr, SWIGTYPE_p_CHAR.getCPtr(value));
    } 
    get {
      IntPtr cPtr = C4dApiPINVOKE.PolyInfo_mark_get(swigCPtr);
      SWIGTYPE_p_CHAR ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_CHAR(cPtr, false);
      return ret;
    } 
  }

  public PolyInfo() : this(C4dApiPINVOKE.new_PolyInfo(), true) {
  }

}

}
