//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum RENDERTARGET {
  RENDERTARGET_ALL = 1000,
  RENDERTARGET_SPECIFIED,
  RENDERTARGET_MINMAX
}

}
