/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

public enum RENDERJOBLIST {
  RENDERJOBLIST_INACTIVE = 1 << 1,
  RENDERJOBLIST_ACTIVE = 1 << 2,
  RENDERJOBLIST_LOAD = 1 << 3,
  RENDERJOBLIST_ALL = 14
}

}
