/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

public enum RENDERRESULT {
  RENDERRESULT_OK = 0,
  RENDERRESULT_OUTOFMEMORY = 1,
  RENDERRESULT_ASSETMISSING = 2,
  RENDERRESULT_SAVINGFAILED = 5,
  RENDERRESULT_USERBREAK = 6,
  RENDERRESULT_GICACHEMISSING = 7,
  RENDERRESULT_NOMACHINE = 9,
  RENDERRESULT_PROJECTNOTFOUND = 1000,
  RENDERRESULT_ERRORLOADINGPROJECT = 1001,
  RENDERRESULT_NOOUTPUTSPECIFIED = 1002
}

}
