/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

public class SWIGTYPE_m_BitmapSaverData__f_r_q_const__Filename_p_BaseBitmap_p_BaseContainer_enum_SAVEBIT__IMAGERESULT {
  private string swigCMemberPtr;

  internal SWIGTYPE_m_BitmapSaverData__f_r_q_const__Filename_p_BaseBitmap_p_BaseContainer_enum_SAVEBIT__IMAGERESULT(string cMemberPtr, bool futureUse) {
    swigCMemberPtr = cMemberPtr;
  }

  protected SWIGTYPE_m_BitmapSaverData__f_r_q_const__Filename_p_BaseBitmap_p_BaseContainer_enum_SAVEBIT__IMAGERESULT() {
    swigCMemberPtr = null;
  }

  internal static string getCMemberPtr(SWIGTYPE_m_BitmapSaverData__f_r_q_const__Filename_p_BaseBitmap_p_BaseContainer_enum_SAVEBIT__IMAGERESULT obj) {
    return obj.swigCMemberPtr;
  }
}

}
