//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public class SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_Int32__p_InclusionTable {
  private string swigCMemberPtr;

  internal SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_Int32__p_InclusionTable(string cMemberPtr, bool futureUse) {
    swigCMemberPtr = cMemberPtr;
  }

  protected SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_Int32__p_InclusionTable() {
    swigCMemberPtr = null;
  }

  internal static string getCMemberPtr(SWIGTYPE_m_iIncludeExcludeData__f_p_BaseDocument_Int32__p_InclusionTable obj) {
    return obj.swigCMemberPtr;
  }
}

}
