/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

using System;
using System.Runtime.InteropServices;

public class SWIGTYPE_m_iIncludeExcludeData__f___LONG {
  private string swigCMemberPtr;

  internal SWIGTYPE_m_iIncludeExcludeData__f___LONG(string cMemberPtr, bool futureUse) {
    swigCMemberPtr = cMemberPtr;
  }

  protected SWIGTYPE_m_iIncludeExcludeData__f___LONG() {
    swigCMemberPtr = null;
  }

  internal static string getCMemberPtr(SWIGTYPE_m_iIncludeExcludeData__f___LONG obj) {
    return obj.swigCMemberPtr;
  }
}

}
