//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public class UVWStruct : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UVWStruct(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UVWStruct obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UVWStruct() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          C4dApiPINVOKE.delete_UVWStruct(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public UVWStruct(SWIGTYPE_p__DONTCONSTRUCT dc) : this(C4dApiPINVOKE.new_UVWStruct__SWIG_0(SWIGTYPE_p__DONTCONSTRUCT.getCPtr(dc)), true) {
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public UVWStruct() : this(C4dApiPINVOKE.new_UVWStruct__SWIG_1(), true) {
  }

  public UVWStruct(Fusee.Math.Core.double3 /* constVector&_cstype */ t_a, Fusee.Math.Core.double3 /* constVector&_cstype */ t_b, Fusee.Math.Core.double3 /* constVector&_cstype */ t_c, Fusee.Math.Core.double3 /* constVector&_cstype */ t_d) : this(C4dApiPINVOKE.new_UVWStruct__SWIG_2(ref t_a /* constVector&_csin */, ref t_b /* constVector&_csin */, ref t_c /* constVector&_csin */, ref t_d /* constVector&_csin */), true) {
  }

  public UVWStruct(Fusee.Math.Core.double3 /* constVector&_cstype */ t_a, Fusee.Math.Core.double3 /* constVector&_cstype */ t_b, Fusee.Math.Core.double3 /* constVector&_cstype */ t_c) : this(C4dApiPINVOKE.new_UVWStruct__SWIG_3(ref t_a /* constVector&_csin */, ref t_b /* constVector&_csin */, ref t_c /* constVector&_csin */), true) {
  }

  public Fusee.Math.Core.double3 /* Vector_cstype_out */ a {
    /* <Vector_csvarin> */
    set 
	{
      C4dApiPINVOKE.UVWStruct_a_set(swigCPtr, value /* Vector_csin */);
    }  /* </Vector_csvarin> */   
   /* <Vector_csvarout> */
   get
   {  
      Fusee.Math.Core.double3 ret = C4dApiPINVOKE.UVWStruct_a_get(swigCPtr);
      return ret;
   } /* <Vector_csvarout> */ 
  }

  public Fusee.Math.Core.double3 /* Vector_cstype_out */ b {
    /* <Vector_csvarin> */
    set 
	{
      C4dApiPINVOKE.UVWStruct_b_set(swigCPtr, value /* Vector_csin */);
    }  /* </Vector_csvarin> */   
   /* <Vector_csvarout> */
   get
   {  
      Fusee.Math.Core.double3 ret = C4dApiPINVOKE.UVWStruct_b_get(swigCPtr);
      return ret;
   } /* <Vector_csvarout> */ 
  }

  public Fusee.Math.Core.double3 /* Vector_cstype_out */ c {
    /* <Vector_csvarin> */
    set 
	{
      C4dApiPINVOKE.UVWStruct_c_set(swigCPtr, value /* Vector_csin */);
    }  /* </Vector_csvarin> */   
   /* <Vector_csvarout> */
   get
   {  
      Fusee.Math.Core.double3 ret = C4dApiPINVOKE.UVWStruct_c_get(swigCPtr);
      return ret;
   } /* <Vector_csvarout> */ 
  }

  public Fusee.Math.Core.double3 /* Vector_cstype_out */ d {
    /* <Vector_csvarin> */
    set 
	{
      C4dApiPINVOKE.UVWStruct_d_set(swigCPtr, value /* Vector_csin */);
    }  /* </Vector_csvarin> */   
   /* <Vector_csvarout> */
   get
   {  
      Fusee.Math.Core.double3 ret = C4dApiPINVOKE.UVWStruct_d_get(swigCPtr);
      return ret;
   } /* <Vector_csvarout> */ 
  }

}

}
