//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public class VariableChanged : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VariableChanged(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VariableChanged obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VariableChanged() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          C4dApiPINVOKE.delete_VariableChanged(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VariableChanged() : this(C4dApiPINVOKE.new_VariableChanged(), true) {
  }

  public int old_cnt {
    set {
      C4dApiPINVOKE.VariableChanged_old_cnt_set(swigCPtr, value);
    } 
    get {
      int ret = C4dApiPINVOKE.VariableChanged_old_cnt_get(swigCPtr);
      return ret;
    } 
  }

  public int new_cnt {
    set {
      C4dApiPINVOKE.VariableChanged_new_cnt_set(swigCPtr, value);
    } 
    get {
      int ret = C4dApiPINVOKE.VariableChanged_new_cnt_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_Int32 map {
    set {
      C4dApiPINVOKE.VariableChanged_map_set(swigCPtr, SWIGTYPE_p_Int32.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = C4dApiPINVOKE.VariableChanged_map_get(swigCPtr);
      SWIGTYPE_p_Int32 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_Int32(cPtr, false);
      return ret;
    } 
  }

  public int vc_flags {
    set {
      C4dApiPINVOKE.VariableChanged_vc_flags_set(swigCPtr, value);
    } 
    get {
      int ret = C4dApiPINVOKE.VariableChanged_vc_flags_get(swigCPtr);
      return ret;
    } 
  }

}

}
