/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

using System;
using System.Runtime.InteropServices;

public class VertexMapTag : VariableTag {
  private HandleRef swigCPtr;

  internal VertexMapTag(IntPtr cPtr, bool cMemoryOwn) : base(C4dApiPINVOKE.VertexMapTag_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(VertexMapTag obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public SWIGTYPE_p_SReal GetDataAddressR() {
    IntPtr cPtr = C4dApiPINVOKE.VertexMapTag_GetDataAddressR(swigCPtr);
    SWIGTYPE_p_SReal ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_SReal(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_SReal GetDataAddressW() {
    IntPtr cPtr = C4dApiPINVOKE.VertexMapTag_GetDataAddressW(swigCPtr);
    SWIGTYPE_p_SReal ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_SReal(cPtr, false);
    return ret;
  }

  public new static VertexMapTag Alloc(int count) {
    IntPtr cPtr = C4dApiPINVOKE.VertexMapTag_Alloc(count);
    VertexMapTag ret = (cPtr == IntPtr.Zero) ? null : new VertexMapTag(cPtr, false);
    return ret;
  }

  public static void Free(SWIGTYPE_p_p_VertexMapTag bl) {
    C4dApiPINVOKE.VertexMapTag_Free(SWIGTYPE_p_p_VertexMapTag.getCPtr(bl));
    if (C4dApiPINVOKE.SWIGPendingException.Pending) throw C4dApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
