//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum VIDEOPOSTINFO {
  VIDEOPOSTINFO_0 = 0,
  VIDEOPOSTINFO_STOREFRAGMENTS = (1 << 0),
  VIDEOPOSTINFO_EXECUTELINE = (1 << 4),
  VIDEOPOSTINFO_EXECUTEPIXEL = (1 << 5),
  VIDEOPOSTINFO_REQUEST_MOTIONMATRIX = (1 << 6),
  VIDEOPOSTINFO_REQUEST_MOTIONGEOMETRY = (1 << 7),
  VIDEOPOSTINFO_CALCVOLUMETRIC = (1 << 8),
  VIDEOPOSTINFO_CALCSHADOW = (1 << 9),
  VIDEOPOSTINFO_CUSTOMLENS = (1 << 10),
  VIDEOPOSTINFO_GLOBALILLUMINATION = (1 << 11),
  VIDEOPOSTINFO_CAUSTICS = (1 << 12),
  VIDEOPOSTINFO_CUSTOMLENS_EXTENDED = (1 << 13),
  VIDEOPOSTINFO_NETFRAME = (1 << 14),
  VIDEOPOSTINFO_NETRUNONSERVER = (1 << 15),
  VIDEOPOSTINFO_NETCREATEBUFFER = (1 << 16)
}

}
