//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace C4d {

public enum VIEWPORT_PICK_FLAGS {
  VIEWPORT_PICK_FLAGS_0 = 0,
  VIEWPORT_PICK_FLAGS_ALLOW_OGL = (1 << 0),
  VIEWPORT_PICK_FLAGS_DONT_STOP_THREADS = (1 << 1),
  VIEWPORT_PICK_FLAGS_USE_SEL_FILTER = (1 << 2),
  VIEWPORT_PICK_FLAGS_OGL_ONLY_TOPMOST = (1 << 3),
  VIEWPORT_PICK_FLAGS_OGL_ONLY_VISIBLE = (1 << 4),
  VIEWPORT_PICK_FLAGS_OGL_IGNORE_Z = (1 << 5),
  VIEWPORT_PICK_FLAGS_OGL_ONLY_TOPMOST_WITH_OBJ = (1 << 6)
}

}
