/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

using System;
using System.Runtime.InteropServices;

public class ViewportPixel : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ViewportPixel(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ViewportPixel obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ViewportPixel() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          C4dApiPINVOKE.delete_ViewportPixel(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public BaseObject op {
    set {
      C4dApiPINVOKE.ViewportPixel_op_set(swigCPtr, BaseObject.getCPtr(value));
    } 
    get {
      IntPtr cPtr = C4dApiPINVOKE.ViewportPixel_op_get(swigCPtr);
      BaseObject ret = (cPtr == IntPtr.Zero) ? null : new BaseObject(cPtr, false);
      return ret;
    } 
  }

  public double z {
    set {
      C4dApiPINVOKE.ViewportPixel_z_set(swigCPtr, value);
    } 
    get {
      double ret = C4dApiPINVOKE.ViewportPixel_z_get(swigCPtr);
      return ret;
    } 
  }

  public int i {
    set {
      C4dApiPINVOKE.ViewportPixel_i_set(swigCPtr, value);
    } 
    get {
      int ret = C4dApiPINVOKE.ViewportPixel_i_get(swigCPtr);
      return ret;
    } 
  }

  public ViewportPixel next {
    set {
      C4dApiPINVOKE.ViewportPixel_next_set(swigCPtr, ViewportPixel.getCPtr(value));
    } 
    get {
      IntPtr cPtr = C4dApiPINVOKE.ViewportPixel_next_get(swigCPtr);
      ViewportPixel ret = (cPtr == IntPtr.Zero) ? null : new ViewportPixel(cPtr, false);
      return ret;
    } 
  }

  public ViewportPixel() : this(C4dApiPINVOKE.new_ViewportPixel(), true) {
  }

}

}
