/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace C4d {

public enum VOLUMEINFO {
  VOLUMEINFO_0 = 0,
  VOLUMEINFO_REFLECTION = 0x00000002,
  VOLUMEINFO_TRANSPARENCY = 0x00000004,
  VOLUMEINFO_ALPHA = 0x00000008,
  VOLUMEINFO_CHANGENORMAL = 0x00002000,
  VOLUMEINFO_DISPLACEMENT = 0x00004000,
  VOLUMEINFO_ENVREQUIRED = 0x00100000,
  VOLUMEINFO_DUDVREQUIRED = 0x00200000,
  VOLUMEINFO_MIPSAT = 0x02000000,
  VOLUMEINFO_VOLUMETRIC = 0x20000000,
  VOLUMEINFO_TRANSFORM = 0x00000010,
  VOLUMEINFO_EVALUATEPROJECTION = 0x04000000,
  VOLUMEINFO_PRIVATE_GLOW = 0x10000000,
  VOLUMEINFO_INITCALCULATION = -1
}

}
