name: Release-Desktop - .NET Core

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    strategy:
      matrix:
        dotnet: [ '3.0.101', '3.1.100' ]
        os: [ 'windows-latest', 'ubuntu-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Build
      run: dotnet build -c Release-Desktop Fusee.sln

    - name: Math tests
      run: dotnet test -c Release src/Tests/Math/Core/Fusee.Test.Math.Core.csproj
