name: Release-Desktop - .NET Core

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        dotnet: [ '3.1.201' ]
        os: [ 'windows-latest', 'ubuntu-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Build
      run: dotnet build -c Release-Desktop Fusee.sln

    - name: Math tests
      run: dotnet test -c Release src/Tests/Math/Core/Fusee.Test.Math.Core.csproj
    
    - name: Upload Player-Artifact
      uses: actions/upload-artifact@v2
      with:
        name: player
        path: bin/Release/Player/Desktop/

    - name: Upload Tool-Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: tools
        path: bin/Release/Tools/

    - name: Upload Example-Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: examples
        path: bin/Release/Examples/**/Desktop/
