#version 460 core

layout(rgba32f, binding = 0) uniform image2D destTex;
layout (local_size_x = 16, local_size_y = 16) in;

void main() {

	// base pixel color for image
	vec4 pixel = vec4(0.0, 0.0, 1.0, 1.0);

	// get index in global work group i.e x,y position
	ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
  
	//
	// interesting stuff happens here later
	//
  
	// output to a specific pixel in the image
	imageStore(destTex, pixel_coords, pixel);
}